### ISSUE TITLE
在SS看到这样的日志，显示有不明用户尝试登录

### ISSUE THREAD

**Issue by loveyanbei** [breakwa11/shadowsocks-rss#60]
RT，日志显示了这样的信息是否意味着GFW正在进行探测？

**Comment by akw28888** [comment]
Where is your log?

**Comment by loveyanbei** [comment]
大概就是日志中显示了wrong password这样的东西，我是用screen运行ssserver的，偶然在标准输出log看到这样的东西，但是那个时间段我从来未输错过密码，我都是用fqrouter和shadowsocks-cs设置过密码，确认准确无误能翻的。出现这种消息是否说明有人在探测？

**Comment by louy2** [comment]
肯定有，至于是谁倒不一定，也没准是 @breakwa11 在测试。

**Comment by breakwa11** [comment]
@louy2 解释一下我在不知道IP的情况下如何针对性测试？不要和我说扫IP，我说的是针对性测试。另外题主没有发log，本来log里面会包含发生错误连接的IP，但在什么数据都没有的情况下做出不合理的猜测，我认为会对它人产生不良影响

**Comment by farrellyang** [comment]
别胡乱猜了，人家怎么获得服务区IP？

**Comment by louy2** [comment]
@breakwa11 对不起，只是看你在测试探测代码，随口一说而已，大家别当真。不过如果是 GFW 跟踪到了 IP，用你的代码探测，症状是 wrong password 吗？

**Comment by falseen** [comment]
@louy2  然而说者无心，听者有意。。。

**Comment by yfdyh000** [comment]
如果是`maybe wrong password`，那不就是无法解码的包吗。

参考 https://github.com/shadowsocks/shadowsocks/issues/410
`如果是常见端口话，我更倾向于这些日志是由普通的端口扫描器造成的，只有比较偏门的端口上出现了这些日志才可能有被刺探的意义。
另外，SS目前遇到错误密码的行为是断开连接，这和大部分正常服务类似，我觉得光从这点上应该很难区分才对。`

**Comment by loveyanbei** [comment]
@breakwa11  信息是 maybe wrong password 错误登录的IP基本都来自中国，分布位置全国各地都有。端口是443

**Comment by yfdyh000** [comment]
@loveyanbei 这不是很正常吗。人家批量扫一下IP段的443端口，看看托管的都是什么网站、证书。你的SS没回复任何信息，并记录了日志。

**Comment by breakwa11** [comment]
端口只要是80或443，都会有中国的各地IP的扫描

**Comment by wyf88** [comment]
I've noticed such logs for quite a long time, and I used to think they are from ordinary port scanner since I'm using port 443. However, today I noticed that the logs have some patterns. When I'm visiting blocked sites like Google heavily, there will be 4 almost simultaneous failed handshake requests from some random IPs of China Unicom / Telecom of some random provinces, and it happens nearly every 12 minutes. In the few hours when I left home, there are only one such failed handshake requests in the log, and after I came back and visited blocked sites heavily, the port scanners came back as well. It's just too coincidental to be a coincidence, and I begin to suspect that they are automated port scanning from the GFW. You can take a look at the log. 

Tue Sep 29 20:37:56 2015 kern.err /usr/bin/ss-server[971]: failed to handshake with 175.19.247.146
Tue Sep 29 20:37:56 2015 kern.err /usr/bin/ss-server[971]: failed to handshake with 27.11.60.77
Tue Sep 29 20:37:56 2015 kern.err /usr/bin/ss-server[971]: failed to handshake with 122.96.23.108
Tue Sep 29 20:37:57 2015 kern.err /usr/bin/ss-server[971]: failed to handshake with 112.117.19.8
Tue Sep 29 20:50:29 2015 kern.err /usr/bin/ss-server[971]: failed to handshake with 1.50.82.235
Tue Sep 29 20:50:39 2015 kern.err /usr/bin/ss-server[971]: failed to handshake with 123.14.251.22
Tue Sep 29 20:50:39 2015 kern.err /usr/bin/ss-server[971]: failed to handshake with 220.174.125.15
Tue Sep 29 21:06:31 2015 kern.err /usr/bin/ss-server[971]: failed to handshake with 14.104.186.233
Tue Sep 29 21:06:31 2015 kern.err /usr/bin/ss-server[971]: failed to handshake with 182.242.105.45
Tue Sep 29 21:06:31 2015 kern.err /usr/bin/ss-server[971]: failed to handshake with 113.247.97.76
Tue Sep 29 21:06:32 2015 kern.err /usr/bin/ss-server[971]: failed to handshake with 123.6.160.50
Tue Sep 29 21:18:10 2015 kern.err /usr/bin/ss-server[971]: failed to handshake with 58.20.99.110
Tue Sep 29 21:18:11 2015 kern.err /usr/bin/ss-server[971]: failed to handshake with 27.10.150.47
Tue Sep 29 21:18:11 2015 kern.err /usr/bin/ss-server[971]: failed to handshake with 123.114.47.19
Tue Sep 29 21:18:11 2015 kern.err /usr/bin/ss-server[971]: failed to handshake with 58.20.98.164

Although my server IP or the port 443 is not yet blocked, I started to experience slow connection to blocked sites sometimes.

**Comment by louy2** [comment]
Yeah... although the IP addresses seem not very correlatable. Any chance you could share a longer list containing such IP's on gist? Do you see any other patterns?

**Comment by wyf88** [comment]
@louy2 Yes, actually these IP addresses are very random from China Unicom / Telecom. The length of my log is very limited because my server is an OpenWrt router. But if you do need a longer list, I will try to save it every hour. [Here](https://gist.github.com/wyf88/f51b5ac3a993569e89b9) is just a short and incomplete list. I sort it and mark with the actual locations.

**Comment by louy2** [comment]
Thank you. If we want to make use of these I think we definitely need a larger force.

**Comment by wyf88** [comment]
@louy2 Thanks for your reply! However, how do you like to make use of these IP addresses of the port scanners? Block them all? I doubt whether that will work. The ISPs have numerous IP addresses, and they can change them easily without much efforts. So in the end we may find the list to be very long. 

As @breakwa11 mentioned, if we use port 80 or 443 on the server side for shadowsocks, it will be probed. I suspect it is related to [this](https://zh.greatfire.org/blog/2015/9月/gfw主动探测系统研究报告). 
What do you think?

**Comment by louy2** [comment]
@wyf88 
Blocking them all doesn't hurt as long as the IP of useful services are not blocked. I'm also curious how long that list can get. Plus, publishing the IP's forces the attackers to change IP, or risk being probed themselves.

Thank you for the link to the updated research.

**Comment by ArianeLu** [comment]
之前有注意到这个问题，对于某些协议，他们会尝试使用不安全的加密方式尝试连接

奇奇怪怪的连接请求全部来自联通骨干网，基本都是在真正的请求发送前到达的，然后...哦不对，测试的时候故意用的是带有特征的协议，所以直接被 reset 了 ←_←
