### ISSUE TITLE
貌似自启动脚本的内容需要改改。

### ISSUE THREAD

**Issue by aescin** [breakwa11/shadowsocks-rss#685]
按照给出的Debian7.x内容，开头是
name=shadowsocks
PY=/usr/bin/python
SS=/usr/local/shadowsocks/server.py
SSPY=server.py
conf=/usr/local/shadowsocks/user-config.json
对应新版本做出修改为
name=shadowsocks
PY=/usr/bin/python
SS=/usr/local/shadowsocksr/server.py
SSPY=server.py
conf=/usr/local/shadowsocksr/user-config.json
保存为/etc/init.d/shadowsocksr

但是每次操作一下三条命令的时候都会报错
/etc/init.d/shadowsocksr start
/etc/init.d/shadowsocksr stop
/etc/init.d/shadowsocksr restart

所以把脚本的内容更改了下
SS=/usr/local/shadowsocks/server.py
改为指向子目录即
SS=/usr/local/shadowsocksr/shadowsocks/server.py。

然后就可以正常运行上述三条命令了。
root@aescin:~# /etc/init.d/shadowsocksr status
shadowsocks is running with PID 1583
root@aescin:~# /etc/init.d/shadowsocksr restart
loaded collections.OrderedDict
IPv6 support
2017-03-04 16:08:54 INFO     shell.py:72 ShadowsocksR 3.0.2 2017-01-08
stopped
shadowsocks stop success
loaded collections.OrderedDict
IPv6 support
2017-03-04 16:08:54 INFO     util.py:85 loading libsodium from libsodium.so.18
2017-03-04 16:08:54 INFO     shell.py:72 ShadowsocksR 3.0.2 2017-01-08
started
shadowsocks start success
root@aescin:~# /etc/init.d/shadowsocksr status
shadowsocks is running with PID 1626
root@aescin:~# /etc/init.d/shadowsocksr stop
loaded collections.OrderedDict
IPv6 support
2017-03-04 16:10:16 INFO     shell.py:72 ShadowsocksR 3.0.2 2017-01-08
stopped
shadowsocks stop success
root@aescin:~# /etc/init.d/shadowsocksr start
loaded collections.OrderedDict
IPv6 support
2017-03-04 16:10:25 INFO     util.py:85 loading libsodium from libsodium.so.18
2017-03-04 16:10:25 INFO     shell.py:72 ShadowsocksR 3.0.2 2017-01-08
started
shadowsocks start success
root@aescin:~# /etc/init.d/shadowsocksr status
shadowsocks is running with PID 1668

**Comment by aescin** [comment]
怎么会有删除线？

**Comment by breakwa11** [comment]
@aescin 你直接去修改就好了

**Comment by KngEast** [comment]
vultr的ubuntu16.04，用以下脚本
[Unit]
Description=ShadowsocksR server
After=network.target
Wants=network.target

[Service]
Type=forking
PIDFile=/var/run/shadowsocks.pid
ExecStart=/usr/bin/python /root/shadowsocksr/shadowsocks/server.py --pid-file /var/run/shadowsocks.pid -c /root/shadowsocksr/user-config.json -d start
ExecStop=/usr/bin/python /root/shadowsocksr/shadowsocks/server.py --pid-file /var/run/shadowsocks.pid -c /root/shadowsocksr/user-config.json -d stop
ExecReload=/bin/kill -HUP $MAINPID
KillMode=process
Restart=always

[Install]
WantedBy=multi-user.target


提示
root@vultr:~# nano /etc/systemd/system/shadowsocks.service
root@vultr:~# systemctl enable shadowsocks.service && systemctl start shadowsocks.service
Created symlink from /etc/systemd/system/multi-user.target.wants/shadowsocks.service to /etc/systemd/system/shadowsocks.service.
Job for shadowsocks.service failed because the control process exited with error code. See "systemctl status shadowsocks.service" and "journalctl -xe" for details.
root@vultr:~# systemctl status shadowsocks.service && journalctl -xe
● shadowsocks.service - ShadowsocksR server
   Loaded: loaded (/etc/systemd/system/shadowsocks.service; enabled; vendor preset: enabled)
   Active: inactive (dead) (Result: exit-code) since Sat 2017-03-18 18:41:17 CST; 31s ago
  Process: 3023 ExecStart=/usr/bin/python /root/shadowsocksr/shadowsocks/server.py --pid-file /var/run/sha

Mar 18 18:41:16 vultr.guest systemd[1]: Starting ShadowsocksR server...
Mar 18 18:41:16 vultr.guest systemd[1]: shadowsocks.service: Control process exited, code=exited status=20
Mar 18 18:41:16 vultr.guest systemd[1]: Failed to start ShadowsocksR server.
Mar 18 18:41:16 vultr.guest systemd[1]: shadowsocks.service: Unit entered failed state.
Mar 18 18:41:16 vultr.guest systemd[1]: shadowsocks.service: Failed with result 'exit-code'.
Mar 18 18:41:17 vultr.guest systemd[1]: shadowsocks.service: Service hold-off time over, scheduling restar
Mar 18 18:41:17 vultr.guest systemd[1]: Stopped ShadowsocksR server.
Mar 18 18:41:17 vultr.guest systemd[1]: shadowsocks.service: Start request repeated too quickly.
Mar 18 18:41:17 vultr.guest systemd[1]: Failed to start ShadowsocksR server.
lines 1-14/14 (END)...skipping...
● shadowsocks.service - ShadowsocksR server
   Loaded: loaded (/etc/systemd/system/shadowsocks.service; enabled; vendor preset: enabled)
   Active: inactive (dead) (Result: exit-code) since Sat 2017-03-18 18:41:17 CST; 31s ago
  Process: 3023 ExecStart=/usr/bin/python /root/shadowsocksr/shadowsocks/server.py --pid-file /var/run/shadowsocks.pid -c /root/shadowsocksr/user-config.json -d start

Mar 18 18:41:16 vultr.guest systemd[1]: Starting ShadowsocksR server...
Mar 18 18:41:16 vultr.guest systemd[1]: shadowsocks.service: Control process exited, code=exited status=203
Mar 18 18:41:16 vultr.guest systemd[1]: Failed to start ShadowsocksR server.
Mar 18 18:41:16 vultr.guest systemd[1]: shadowsocks.service: Unit entered failed state.
Mar 18 18:41:16 vultr.guest systemd[1]: shadowsocks.service: Failed with result 'exit-code'.
Mar 18 18:41:17 vultr.guest systemd[1]: shadowsocks.service: Service hold-off time over, scheduling restart.
Mar 18 18:41:17 vultr.guest systemd[1]: Stopped ShadowsocksR server.
Mar 18 18:41:17 vultr.guest systemd[1]: shadowsocks.service: Start request repeated too quickly.
Mar 18 18:41:17 vultr.guest systemd[1]: Failed to start ShadowsocksR server

这个怎么解决啊？

**Comment by mixool** [comment]
为了搞定自启动，按着教程搞不定。。。羞耻的用上了一键包。。。

**Comment by imtyz001** [comment]
我结合自己的使用情况，修改了一下CentOS7使用的单用户自启动脚本
